/**
 * Progressive Bot Generator
 * Generates bots step-by-step with validation and adaptation
 */

import { DeepSeekClient } from '../core/deepseek_client.js';
import { PromptBuilder } from './prompt_builder.js';
import { TemplateManager } from './template_manager.js';
import { BotExecutor } from '../executors/bot_executor.js';
import { SandboxExecutor } from '../executors/sandbox_executor.js';
import type { BotFiles, GeneratedStepInfo, BotGenerationContext } from '../types/bot.js';
import type { PageAnalysis } from '../types/analysis.js';
import { writeFile, sanitizeBotName } from '../utils/file_helpers.js';
import { BotStorageManager, BotMetadata } from '../utils/bot_storage.js';
import * as yaml from 'js-yaml';
import * as readline from 'readline';
import * as fs from 'fs/promises';

export class BotGenerator {

  private deepseek: DeepSeekClient;
  private promptBuilder: PromptBuilder;
  private templateManager: TemplateManager;
  private botExecutor: BotExecutor | null = null;  // Official bot runner
  private sandbox: SandboxExecutor;                 // Testing environment
  private storage: BotStorageManager;
  private currentBotId: string | null = null;
  private currentBotName: string | null = null;
  private currentOutputDir: string | null = null;

  constructor(deepseekApiKey: string) {
    this.deepseek = new DeepSeekClient(deepseekApiKey);
    this.promptBuilder = new PromptBuilder();
    this.templateManager = new TemplateManager();
    this.sandbox = new SandboxExecutor();
    this.storage = new BotStorageManager();
  }

  async generateBot(
    url: string,
    intent: string,
    options?: {
      botName?: string;
      allowManualLogin?: boolean;
      useSession?: boolean;
      existingBotId?: string;
      additionalContext?: string;
    }
  ): Promise<BotFiles> {
    // Ensure URL has protocol
    if (!url.startsWith('http://') && !url.startsWith('https://')) {
      url = 'https://' + url;
    }

    // Load existing bot if continuing
    let existingBot: BotMetadata | null = null;
    if (options?.existingBotId) {
      existingBot = await this.storage.loadBotMetadata(options.existingBotId);
      if (existingBot) {
        console.log('\n📂 Loading existing bot...');
        console.log(`🤖 Bot: ${existingBot.name}`);
        console.log(`📍 URL: ${existingBot.url}`);
        console.log(`🎯 Original Intent: ${existingBot.original_intent}`);
        console.log(`📊 Progress: ${existingBot.current_step}/${existingBot.total_steps} steps`);
        if (options.additionalContext) {
          console.log(`💬 Additional Context: ${options.additionalContext}`);
        }
        console.log('');

        // Display detailed progress summary
        await this.displayProgressSummary(existingBot, options.additionalContext);
      }
    }

    if (!existingBot) {
      console.log('\n🤖 Starting Progressive Bot Generation...');
      console.log(`📍 Target URL: ${url}`);
      console.log(`🎯 User Intent: ${intent}\n`);

      // Initialize bot from templates
      const botName = sanitizeBotName(options?.botName || intent);
      const outputDir = `./generated_bots/${botName}`;

      await this.templateManager.initializeBotFromTemplate(botName, url, intent, outputDir);

      console.log(`📂 Bot initialized with standard template structure`);
      console.log(`   • Step 0: init_context (load config, selectors)`);
      console.log(`   • Step 1: navigate_to_homepage (open URL)`);
      console.log(`   • Steps 2+: Will be generated by AI\n`);
    }

    // Create or restore context
    const context: BotGenerationContext = existingBot ? {
      intent: existingBot.original_intent,
      url: existingBot.url,
      generated_steps: existingBot.generated_steps as any[],
      current_step: existingBot.current_step
    } : {
      intent,
      url,
      generated_steps: [],
      current_step: 2 // Start at 2 because steps 0 and 1 are in the template
    };

    // Generate bot ID and store bot info
    this.currentBotId = options?.existingBotId || this.storage.generateBotId();
    this.currentBotName = existingBot?.name || sanitizeBotName(options?.botName || intent);
    this.currentOutputDir = `./generated_bots/${this.currentBotName}`;

    try {
      // PHASE 1: Execute Template Steps (0, 1, 2) using BotExecutor
      if (!existingBot) {
        console.log('═══════════════════════════════════════════════════════');
        console.log('PHASE 1: EXECUTE TEMPLATE STEPS');
        console.log('═══════════════════════════════════════════════════════\n');

        await this.executeTemplateSteps(context);

        // Save initial metadata
        await this.saveBotProgress(context, url, intent, this.currentBotName);
      } else {
        // For existing bots, still need to initialize and navigate
        console.log('═══════════════════════════════════════════════════════');
        console.log('PHASE 1: RESUME EXISTING BOT');
        console.log('═══════════════════════════════════════════════════════\n');

        await this.initializeBotExecutor();

        // Execute steps up to current position
        await this.botExecutor!.executeStep('init_context');
        await this.botExecutor!.executeStep('navigate_to_homepage');

        const loginResult = await this.botExecutor!.executeStep('detect_login_state');
        if (loginResult === 'login_required') {
          await this.promptUserForLogin();
          await this.botExecutor!.executeStep('wait_for_manual_login');
        }
      }

      // PHASE 2: Initialize Sandbox and Generate Workflow Steps
      console.log('\n═══════════════════════════════════════════════════════');
      console.log('PHASE 2: ITERATIVE GENERATION WITH TESTING');
      if (options?.additionalContext) {
        console.log(`💬 User Guidance: ${options.additionalContext}`);
      }
      console.log('═══════════════════════════════════════════════════════\n');

      // Initialize sandbox executor (shares page with bot executor)
      await this.initializeSandboxExecutor();

      const workflowSteps = await this.generateWorkflowPhase(context, options?.additionalContext);
      context.generated_steps.push(...workflowSteps);

      // Save progress after each phase
      await this.saveBotProgress(context, url, intent, this.currentBotName!);

      // PHASE 3: Compile Bot
      console.log('\n═══════════════════════════════════════════════════════');
      console.log('PHASE 3: COMPILING BOT');
      console.log('═══════════════════════════════════════════════════════\n');

      const botFiles = await this.compileBotFiles(context, this.currentBotName!);

      // Mark bot as completed
      await this.storage.updateBotStatus(this.currentBotId!, 'completed');

      console.log('✅ Bot generation complete!\n');

      return botFiles;

    } finally {
      // Cleanup executors
      try {
        if (this.botExecutor) {
          console.log('\n🧹 Closing bot executor...');
          await this.botExecutor.close();
        }
        if (this.sandbox) {
          console.log('🧹 Closing sandbox executor...');
          await this.sandbox.close();
        }
      } catch (error) {
        console.warn('⚠️  Failed to close executors:', error);
      }
    }
  }

  async waitForManualLogin(url: string): Promise<void> {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      console.log('\n╔═══════════════════════════════════════════════════════════════╗');
      console.log('║                     MANUAL LOGIN REQUIRED                     ║');
      console.log('╚═══════════════════════════════════════════════════════════════╝\n');
      console.log(`🔐 Please login to ${url} in the browser window`);
      console.log('⏳ Take your time to complete the login process...\n');

      rl.question('✅ Press ENTER when you\'re logged in and ready to continue... ', () => {
        rl.close();
        console.log('\n🚀 Continuing with bot generation...\n');
        resolve();
      });
    });
  }

  /**
   * Initialize BotExecutor with generated bot files
   */
  private async initializeBotExecutor(): Promise<void> {
    console.log('🚀 Initializing BotExecutor...');

    this.botExecutor = new BotExecutor(this.currentOutputDir!, this.currentBotName!);
    await this.botExecutor.initialize(false); // headless = false for debugging

    console.log('✅ BotExecutor initialized\n');
  }

  /**
   * Execute template steps (0, 1) using BotExecutor
   * Step 2 (detect_login_state) will be AI-generated as the first custom step
   */
  private async executeTemplateSteps(context: BotGenerationContext): Promise<void> {
    // Initialize bot executor
    await this.initializeBotExecutor();

    console.log('▶️  Executing template steps...\n');

    // Step 0: Initialize context
    console.log('📦 Step 0: init_context');
    await this.botExecutor!.executeStep('init_context');

    // Step 1: Navigate to homepage
    console.log('🌐 Step 1: navigate_to_homepage');
    await this.botExecutor!.executeStep('navigate_to_homepage');

    console.log('\n✅ Template steps 0-1 executed');
    console.log('🤖 AI will now generate step 2 (login detection) based on actual page HTML\n');
  }

  /**
   * Initialize SandboxExecutor for testing AI-generated steps
   */
  private async initializeSandboxExecutor(): Promise<void> {
    console.log('🧪 Initializing SandboxExecutor for testing...');

    // Initialize sandbox with its own browser
    // It will test steps before they're committed to the bot
    await this.sandbox.initialize(false, false, ''); // Don't navigate

    console.log('✅ SandboxExecutor ready for testing\n');
  }

  /**
   * Prompt user to login manually
   */
  private async promptUserForLogin(): Promise<void> {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      console.log('');
      rl.question('✅ Press ENTER when you have logged in... ', () => {
        rl.close();
        console.log('');
        resolve();
      });
    });
  }

  private async askClarifyingQuestions(questions: string[]): Promise<Record<string, string>> {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      const answers: Record<string, string> = {};
      let currentIndex = 0;

      const askNext = () => {
        if (currentIndex >= questions.length) {
          rl.close();
          resolve(answers);
          return;
        }

        const question = questions[currentIndex];
        rl.question(`❓ ${question}\n   Answer: `, (answer) => {
          answers[question] = answer.trim();
          currentIndex++;
          console.log('');
          askNext();
        });
      };

      console.log('\n💬 I have a few questions to better understand your goal:\n');
      askNext();
    });
  }

  /**
   * Display progress summary when continuing a bot
   */
  private async displayProgressSummary(
    bot: BotMetadata,
    additionalContext?: string
  ): Promise<void> {
    console.log('╔═══════════════════════════════════════════════════════════════╗');
    console.log('║                     PROGRESS SUMMARY                          ║');
    console.log('╚═══════════════════════════════════════════════════════════════╝\n');

    // What's been done
    console.log('✅ COMPLETED STEPS:\n');
    const completedSteps = (bot.generated_steps || []).filter(
      (_, idx) => idx < bot.current_step - 1
    );

    if (completedSteps.length === 0) {
      console.log('   (No steps completed yet - bot just started)\n');
    } else {
      completedSteps.forEach((step, idx) => {
        const status = step.execution_result?.success ? '✅' : '❌';
        console.log(`   ${idx + 1}. ${status} ${step.action_description}`);
      });
      console.log('');
    }

    // Current state
    console.log('📍 CURRENT STATE:\n');
    if (bot.current_step <= bot.total_steps) {
      const currentStep = (bot.generated_steps || [])[bot.current_step - 1];
      if (currentStep) {
        console.log(`   Step ${bot.current_step}: ${currentStep.action_description}`);
        if (currentStep.execution_result?.error) {
          console.log(`   ⚠️  Last error: ${currentStep.execution_result.error}`);
        }
      } else {
        console.log(`   Ready to generate step ${bot.current_step}`);
      }
    } else {
      console.log('   All steps completed - ready for new workflow');
    }
    console.log('');

    // What's next
    console.log('🎯 RECOMMENDED NEXT ACTIONS:\n');

    // Analyze bot state and provide recommendations
    const recommendations = this.analyzeAndRecommend(bot, additionalContext);
    recommendations.forEach((rec, idx) => {
      console.log(`   ${idx + 1}. ${rec}`);
    });
    console.log('');

    // Issues encountered
    const failedSteps = (bot.generated_steps || []).filter(
      step => step.execution_result?.success === false
    );

    if (failedSteps.length > 0) {
      console.log('⚠️  ISSUES ENCOUNTERED:\n');
      failedSteps.forEach((step, idx) => {
        console.log(`   • Step ${step.step_number}: ${step.action_description}`);
        if (step.execution_result?.error) {
          console.log(`     Error: ${step.execution_result.error}`);
        }
      });
      console.log('');
    }

    console.log('─────────────────────────────────────────────────────────────\n');
    console.log('💡 The bot will continue from where it left off.\n');

    if (additionalContext) {
      console.log(`📝 Your additional guidance: "${additionalContext}"\n`);
    }
  }

  /**
   * Analyze bot state and provide smart recommendations
   */
  private analyzeAndRecommend(
    bot: BotMetadata,
    additionalContext?: string
  ): string[] {
    const recommendations: string[] = [];

    // ALWAYS start with the goal
    recommendations.push('🎯 GOAL: Find and apply to jobs');

    // Check if bot is stuck (multiple failures on same step)
    const recentSteps = bot.generated_steps.slice(-3);
    const allFailed = recentSteps.every(step => step.execution_result?.success === false);

    if (allFailed && recentSteps.length > 0) {
      recommendations.push('🔧 Bot appears stuck - rethink the approach');
      recommendations.push('💬 Provide specific guidance or let AI analyze HTML again');
      return recommendations;
    }

    // Check completion status
    if (bot.status === 'completed') {
      recommendations.push('✨ Bot completed - jobs should be applied to');
      recommendations.push('📊 Review results and check applications');
      return recommendations;
    }

    // Check if additional guidance provided
    if (additionalContext) {
      recommendations.push(`📝 User guidance: "${additionalContext}"`);
      recommendations.push('🤖 Generate next micro-plan with this context');
      return recommendations;
    }

    // Analyze what's actually been done
    const hasNavigated = bot.generated_steps.some(s =>
      s.action_description.toLowerCase().includes('navigate') ||
      s.action_description.toLowerCase().includes('homepage')
    );

    const hasSearched = bot.generated_steps.some(s =>
      s.action_description.toLowerCase().includes('search') ||
      s.action_description.toLowerCase().includes('jobs')
    );

    const hasCollectedCards = bot.generated_steps.some(s =>
      s.action_description.toLowerCase().includes('card') ||
      s.action_description.toLowerCase().includes('collect')
    );

    const hasApplied = bot.generated_steps.some(s =>
      s.action_description.toLowerCase().includes('apply')
    );

    // Give recommendations based on what's actually missing
    if (!hasNavigated) {
      recommendations.push('📍 Next: Navigate to job site homepage');
      recommendations.push('🔍 Analyze the page to understand structure');
    } else if (!hasSearched) {
      recommendations.push('🔍 Next: Find and use search functionality');
      recommendations.push('⌨️  Enter job search criteria');
    } else if (!hasCollectedCards) {
      recommendations.push('📋 Next: Find job cards on the page');
      recommendations.push('🤖 Use AI-powered pattern detection');
    } else if (!hasApplied) {
      recommendations.push('✅ Next: Click on job cards and apply');
      recommendations.push('🚀 Detect Quick Apply vs Regular Apply');
    } else {
      recommendations.push('🔄 Next: Continue applying to more jobs');
      recommendations.push('📄 Move to next page if needed');
    }

    return recommendations;
  }

  /**
   * Display a generic plan to the user
   */
  private displayGenericPlan(plan: any): void {
    console.log('\n╔═══════════════════════════════════════════════════════════════╗');
    console.log('║                    GENERIC EXECUTION PLAN                     ║');
    console.log('╚═══════════════════════════════════════════════════════════════╝\n');

    console.log(`🎯 Goal: ${plan.goal}`);
    console.log(`⏱️  Estimated duration: ${plan.estimated_duration}\n`);

    console.log('📋 Phases:\n');
    plan.phases.forEach((phase: any, index: number) => {
      const required = phase.required ? '🔴 REQUIRED' : '🟡 OPTIONAL';
      console.log(`${index + 1}. ${phase.phase} ${required}`);
      console.log(`   ${phase.description}\n`);

      console.log(`   Primary Strategies:`);
      phase.strategies.forEach((strategy: string) => {
        console.log(`   • ${strategy}`);
      });

      if (phase.fallbacks && phase.fallbacks.length > 0) {
        console.log(`\n   Fallback Strategies:`);
        phase.fallbacks.forEach((fallback: string) => {
          console.log(`   ↳ ${fallback}`);
        });
      }
      console.log('');
    });

    if (plan.warnings && plan.warnings.length > 0) {
      console.log('⚠️  Warnings:');
      plan.warnings.forEach((warning: string) => {
        console.log(`   • ${warning}`);
      });
      console.log('');
    }
  }

  /**
   * Prompt user for plan action (approve/modify/cancel)
   */
  private async promptPlanAction(): Promise<'approve' | 'modify' | 'cancel'> {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      rl.question('👉 [A]pprove / [M]odify / [C]ancel? ', (answer) => {
        rl.close();
        const choice = answer.toLowerCase().trim();

        if (choice === 'a' || choice === 'approve') {
          resolve('approve');
        } else if (choice === 'm' || choice === 'modify') {
          resolve('modify');
        } else if (choice === 'c' || choice === 'cancel') {
          resolve('cancel');
        } else {
          // Default to approve if unclear
          console.log('Invalid choice, assuming approve...\n');
          resolve('approve');
        }
      });
    });
  }

  /**
   * Get user feedback for plan modification
   */
  private async getUserPlanFeedback(): Promise<string> {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      console.log('\n💬 What would you like to change about the plan?');
      console.log('(e.g., "Add a filter phase", "Skip the login step", "Focus more on quick apply jobs")\n');

      rl.question('Your feedback: ', (feedback) => {
        rl.close();
        resolve(feedback.trim());
      });
    });
  }

  /**
   * Create a CLI sticky todo list from the plan
   */
  private async createCliTodoList(plan: any): Promise<void> {
    console.log('📝 Creating task list for execution:\n');
    console.log('╭─────────────────────────────────────────────────────────────╮');
    console.log('│                       TODO LIST                             │');
    console.log('╰─────────────────────────────────────────────────────────────╯\n');

    plan.phases.forEach((phase: any, index: number) => {
      const checkbox = '☐';
      const required = phase.required ? '[REQUIRED]' : '[OPTIONAL]';
      console.log(`${checkbox} ${index + 1}. ${phase.phase} ${required}`);
      console.log(`   ${phase.description}`);
      console.log('');
    });

    console.log('─────────────────────────────────────────────────────────────\n');
    console.log('💡 This task list will guide the execution.\n');
  }

  // REMOVED: generateDiscoveryPhase - now using BotExecutor to execute template steps directly

  /**
   * Generate workflow using an iterative, test-before-commit process.
   * Each step is tested in SandboxExecutor before being committed to bot files.
   *
   * Note: Steps 0, 1 are pre-defined in the template. AI generation starts at step 2 (login detection).
   */
  private async generateWorkflowPhase(context: BotGenerationContext, additionalContext?: string): Promise<GeneratedStepInfo[]> {
    const steps: GeneratedStepInfo[] = [];
    const maxSteps = 30; // Set a hard limit for total steps
    let stepCounter = 0;

    console.log('\n╔═══════════════════════════════════════════════════════════════╗');
    console.log('║      ITERATIVE GENERATION WITH SANDBOX TESTING              ║');
    console.log('╚═══════════════════════════════════════════════════════════════╝\n');
    console.log('🎯 GOAL:', context.intent);
    console.log('📋 Strategy: Generate → Test in Sandbox → Commit → Execute');
    console.log('ℹ️  Steps 0-1 already executed (template steps)');
    console.log('🤖 First AI task: Generate step 2 (login detection)\n');

    while (stepCounter < maxSteps) {
      // currentStepNumber starts at 2 (0, 1 are template steps)
      const currentStepNumber = context.generated_steps.length + 2;
      stepCounter++;

      console.log(`\n═══════════════════════════════════════════════════════`);
      console.log(`GENERATING STEP #${currentStepNumber}`);
      console.log(`═══════════════════════════════════════════════════════\n`);

      // Get current page state from BotExecutor (the real, running bot)
      const pageState = await this.botExecutor!.getPageState();
      const currentPage = this.botExecutor!.getPage();
      const completedSteps = context.generated_steps.map(s => s.action_description);

      // Check if goal is already fulfilled
      const isFulfilled = await this.deepseek.isIntentFulfilled(context.intent, {
        title: pageState.title,
        url: pageState.url,
        visible_text: await currentPage.innerText('body').catch(() => '')
      });

      if (isFulfilled) {
        console.log('🎉 GOAL ACHIEVED! The user\'s intent has been fulfilled.\n');
        break;
      }

      // AI analyzes page and generates next step
      console.log('🤖 Analyzing page and generating next action...');

      let generatedStep;

      // Special handling for step 2 (login detection)
      if (currentStepNumber === 2) {
        console.log('🔍 Generating site-specific login detection step...');
        generatedStep = await this.generateLoginDetectionStep(pageState, context.url);
      } else {
        // Regular step generation
        const stepPrompt = this.promptBuilder.buildStepPrompt(
          context.intent,
          {
            raw_html: pageState.html,
            url: pageState.url,
            title: pageState.title
          },
          {
            stepNumber: currentStepNumber,
            previousAction: completedSteps[completedSteps.length - 1],
            context: additionalContext || `Based on the current page HTML, decide the single best next action to achieve the goal: ${context.intent}.`,
            completedSteps,
          }
        );

        generatedStep = await this.deepseek.generateStep(stepPrompt);
      }
      const actionDescription = this.extractActionDescription(generatedStep) || `Generated Step ${currentStepNumber}`;
      const functionName = this.extractFunctionName(generatedStep.typescript);

      console.log(`💡 AI suggests: ${actionDescription}`);

      // Ask user for approval
      const approved = await this.confirmNextStep(actionDescription);
      if (!approved) {
        console.log('❌ Step rejected by user. Stopping generation.\n');
        break;
      }

      // TEST in sandbox first (test-before-commit pattern)
      console.log(`\n🧪 Testing in sandbox...`);
      const testResult = await this.testStepInSandbox(
        generatedStep.typescript,
        functionName,
        pageState
      );

      if (testResult.success) {
        console.log(`✅ Sandbox test PASSED!\n`);

        // Step passed testing - commit to bot files
        console.log(`📝 Committing step ${currentStepNumber} to bot files...`);
        await this.commitStepToBotFiles(currentStepNumber, generatedStep);

        // Reload BotExecutor to pick up the new step
        console.log(`🔄 Reloading BotExecutor...`);
        await this.botExecutor!.reloadEngine();

        // Execute the step in the official bot
        console.log(`▶️  Executing step in BotExecutor...`);
        const stepKey = currentStepNumber === 2 ? 'detect_login_state' : `step_${currentStepNumber}`;
        const stepResult = await this.botExecutor!.executeStep(stepKey);

        // Special handling for step 2 (login detection)
        if (currentStepNumber === 2 && stepResult === 'login_required') {
          console.log('\n🔐 Login required detected!');
          await this.promptUserForLogin();
          console.log('🔐 Executing step 2.5: wait_for_manual_login');
          await this.botExecutor!.executeStep('wait_for_manual_login');
          console.log('✅ Login complete, continuing...\n');
        }

        // Store step info
        const newStep: GeneratedStepInfo = {
          step_number: currentStepNumber,
          yaml: generatedStep.yaml,
          typescript: generatedStep.typescript,
          action_description: actionDescription,
          execution_result: { success: true }
        };
        steps.push(newStep);
        context.generated_steps.push(newStep);

        console.log(`✅ Step ${currentStepNumber} complete!\n`);

      } else {
        console.log(`❌ Sandbox test FAILED: ${testResult.error}\n`);
        console.log('🔄 Will ask AI to fix and regenerate...\n');

        // TODO: Implement retry with AI fix
        // For now, we'll just skip and continue
        stepCounter--; // Don't count this as a step
        continue;
      }

      // Save progress
      await this.saveBotProgress(context, context.url, context.intent, this.currentBotName!);
      await new Promise(resolve => setTimeout(resolve, 1000));
    }

    if (stepCounter >= maxSteps) {
      console.log('⚠️  Maximum step limit reached. Stopping generation.');
    }

    return steps;
  }

  /**
   * Generate login detection step (step 2) with special AI prompt
   */
  private async generateLoginDetectionStep(
    pageState: { html: string; url: string; title: string },
    targetUrl: string
  ): Promise<{ yaml: string; typescript: string }> {
    const prompt = `You are generating a SITE-SPECIFIC login detection function for ${targetUrl}.

GOAL: Create a detect_login_state() function that accurately determines if the user is logged in.

CURRENT PAGE HTML (analyze this to find login indicators):
${pageState.html.substring(0, 50000)}

REQUIREMENTS:
1. Analyze the HTML to find site-specific login/logout indicators
2. Look for selectors like:
   - Profile menus, avatars, user names
   - "Sign Out" or "Log Out" buttons
   - "Sign In" or "Log In" buttons/links
   - Data attributes (data-testid, data-test, etc.)
3. Use Playwright locators (NOT text search)
4. Return one of: 'logged_in', 'login_required', or 'detection_failed'
5. Log your reasoning with console.log

YAML FORMAT (step_2):
\`\`\`yaml
detect_login_state:
  step: 2
  func: "detect_login_state"
  transitions:
    logged_in: "step_3"
    login_required: "wait_for_manual_login"
    detection_failed: "step_3"
  timeout: 15
  on_timeout_event: "detection_failed"
\`\`\`

TYPESCRIPT FORMAT:
\`\`\`typescript
export async function* detect_login_state(ctx: any): AsyncGenerator<string, void> {
  const page: Page = ctx.page;

  console.log('🔍 Detecting login state for ${targetUrl}...');

  try {
    // Check for logged-in indicators
    const profileMenu = await page.locator('[data-test="profile-menu"]').count();
    const userAvatar = await page.locator('img[alt*="avatar" i]').count();

    // Check for login prompts
    const signInButton = await page.locator('a:has-text("Sign in")').count();

    console.log(\`  Profile menu: \${profileMenu > 0 ? '✓' : '✗'}\`);
    console.log(\`  Sign in button: \${signInButton > 0 ? '✓' : '✗'}\`);

    if (profileMenu > 0 || userAvatar > 0) {
      console.log('✅ User is logged in');
      yield 'logged_in';
    } else if (signInButton > 0) {
      console.log('🔐 Login required');
      yield 'login_required';
    } else {
      console.log('⚠️  Unclear, assuming logged in');
      yield 'logged_in';
    }
  } catch (error: any) {
    console.error(\`❌ Detection failed: \${error.message}\`);
    yield 'detection_failed';
  }
}
\`\`\`

Generate the YAML and TypeScript for this site-specific login detection step.`;

    return await this.deepseek.generateStep(prompt);
  }

  /**
   * Test a generated step in the sandbox before committing
   */
  private async testStepInSandbox(
    typescript: string,
    functionName: string,
    currentPageState: { html: string; url: string; title: string }
  ): Promise<{ success: boolean; error?: string }> {
    try {
      // Execute the step in sandbox
      const result = await this.executeGeneratedStep(typescript, functionName);
      return result;
    } catch (error: any) {
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Commit a tested step to the bot files
   */
  private async commitStepToBotFiles(
    stepNumber: number,
    generatedStep: { yaml: string; typescript: string }
  ): Promise<void> {
    const tsImplPath = `${this.currentOutputDir}/${this.currentBotName}_impl.ts`;
    const yamlPath = `${this.currentOutputDir}/${this.currentBotName}_steps.yaml`;

    // 1. Append to TypeScript implementation file
    await fs.appendFile(tsImplPath, `\n${generatedStep.typescript}\n`);

    // 2. Update YAML workflow file
    try {
      const yamlFileContent = await fs.readFile(yamlPath, 'utf8');
      const mainWorkflow = yaml.load(yamlFileContent) as any;
      const stepWorkflow = yaml.load(generatedStep.yaml) as any;

      const stepKey = Object.keys(stepWorkflow)[0];
      if (stepKey) {
        mainWorkflow.steps_config[stepKey] = stepWorkflow[stepKey];

        // Link previous step to this one
        if (stepNumber === 2) {
          // Step 2 is detect_login_state - YAML already in template
          // Just update the function (it was AI-generated)
          // Transitions are already defined in template
        } else if (stepNumber === 3) {
          // Link detect_login_state (step 2) to step 3
          if (mainWorkflow.steps_config['detect_login_state']) {
            mainWorkflow.steps_config['detect_login_state'].transitions.logged_in = stepKey;
          }
        } else if (stepNumber > 3) {
          const prevStepKey = `step_${stepNumber - 1}`;
          if (mainWorkflow.steps_config[prevStepKey]) {
            mainWorkflow.steps_config[prevStepKey].transitions.success = stepKey;
          }
        }
      }

      const updatedYamlContent = yaml.dump(mainWorkflow);
      await writeFile(yamlPath, updatedYamlContent);
      console.log(`   ✓ Committed to ${this.currentBotName}_impl.ts`);
      console.log(`   ✓ Committed to ${this.currentBotName}_steps.yaml`);
    } catch (e) {
      console.error(`❌ Failed to update YAML file:`, e);
      throw e;
    }
  }

  /**
   * Confirm the next step with the user
   */
  private async confirmNextStep(action: string): Promise<boolean> {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      console.log('\nNext Action Proposed:');
      console.log(`   ➡️  ${action}\n`);

      rl.question('👉 Execute this step? [Y/n]: ', (answer) => {
        rl.close();
        const approved = !answer.trim() || answer.toLowerCase().trim().startsWith('y');
        console.log('');
        resolve(approved);
      });
    });
  }

  private async executeGeneratedStep(
    typescript: string,
    functionName: string
  ): Promise<any> {
    try {
      console.log(`🧪 Executing step function: ${functionName}`);

      // Extract selector from generated code
      const selector = this.extractPrimarySelector(typescript);

      if (selector) {
        console.log(`🎯 Using selector: ${selector}`);

        const page = this.sandbox.getPage();

        // Wait for element and interact with it
        try {
          const element = await page.waitForSelector(selector, {
            timeout: 10000,
            state: 'visible'
          });

          if (!element) {
            throw new Error(`Element not found: ${selector}`);
          }

          // Determine action based on function name or element type
          const tagName = await element.evaluate(el => el.tagName.toLowerCase());

          // Determine action type
          let actionTaken = false;

          if (functionName.includes('click') || functionName.includes('button') || tagName === 'button' || tagName === 'a') {
            console.log(`👆 Clicking element...`);
            await element.click();
            await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
            actionTaken = true;
          } else if (functionName.includes('fill') || functionName.includes('type') || functionName.includes('input') || tagName === 'input' || tagName === 'textarea') {
            console.log(`⌨️  Filling input...`);
            // Extract value from code if present
            const valueMatch = typescript.match(/fill\(['"]([^'"]+)['"]\)/) || typescript.match(/type\(['"]([^'"]+)['"]\)/);
            const value = valueMatch ? valueMatch[1] : 'software engineer';
            await element.fill(value);
            actionTaken = true;
          } else if (functionName.includes('press') && functionName.includes('enter')) {
            console.log(`⏎ Pressing Enter...`);
            await element.press('Enter');
            await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
            actionTaken = true;
          } else if (functionName.includes('select') || tagName === 'select') {
            console.log(`📋 Selecting option...`);
            await element.selectOption({ index: 0 });
            actionTaken = true;
          } else {
            console.log(`👀 Element found but no clear action determined`);
            console.log(`   Function name: ${functionName}, Tag: ${tagName}`);
          }

          if (!actionTaken) {
            console.log(`⚠️  No action was taken on the element`);
            return {
              success: false,
              error: 'Element found but no action could be determined',
              event: 'no_action',
              page_state: await this.sandbox.capturePageState()
            };
          }

          // Wait a bit for any dynamic changes
          await new Promise(resolve => setTimeout(resolve, 2000));

          console.log(`✅ Action completed successfully`);

          return {
            success: true,
            event: 'success_event',
            page_state: await this.sandbox.capturePageState()
          };

        } catch (error: any) {
          console.error(`❌ Selector failed: ${error.message}`);

          // Try fallback selectors if available
          const fallbacks = this.extractFallbackSelectors(typescript);
          for (const fallbackSelector of fallbacks.slice(0, 2)) {
            console.log(`🔄 Trying fallback: ${fallbackSelector}`);
            try {
              const element = await page.waitForSelector(fallbackSelector, {
                timeout: 5000,
                state: 'visible'
              });

              if (element) {
                await element.click();
                console.log(`✅ Fallback succeeded`);
                await new Promise(resolve => setTimeout(resolve, 1500));

                return {
                  success: true,
                  event: 'success_event',
                  page_state: await this.sandbox.capturePageState()
                };
              }
            } catch (e) {
              // Try next fallback
            }
          }

          throw error;
        }
      } else {
        console.log(`⚠️  No selector found in generated code`);
        console.log(`❌ Cannot execute step - no selector to interact with`);
        return {
          success: false,
          error: 'No selector found in generated code',
          event: 'element_not_found',
          page_state: await this.sandbox.capturePageState()
        };
      }

    } catch (error: any) {
      return {
        success: false,
        error: error.message,
        page_state: await this.sandbox.capturePageState()
      };
    }
  }

  private extractPrimarySelector(typescript: string): string | null {
    // Try to find waitForSelector or similar
    const selectorMatch = typescript.match(/waitForSelector\(['"]([^'"]+)['"]/);
    if (selectorMatch) {
      console.log(`   Found waitForSelector: ${selectorMatch[1]}`);
      return selectorMatch[1];
    }

    // Try to find locator
    const locatorMatch = typescript.match(/locator\(['"]([^'"]+)['"]/);
    if (locatorMatch) {
      console.log(`   Found locator: ${locatorMatch[1]}`);
      return locatorMatch[1];
    }

    // Try to find page.locator
    const pageLocatorMatch = typescript.match(/page\.locator\(['"]([^'"]+)['"]/);
    if (pageLocatorMatch) {
      console.log(`   Found page.locator: ${pageLocatorMatch[1]}`);
      return pageLocatorMatch[1];
    }

    // Try to find click/fill directly
    const directMatch = typescript.match(/(?:click|fill)\(['"]([^'"]+)['"]/);
    if (directMatch) {
      console.log(`   Found in click/fill: ${directMatch[1]}`);
      return directMatch[1];
    }

    // Try to find $$ selector
    const clickMatch = typescript.match(/\$\$?\(['"]([^'"]+)['"]\)/);
    if (clickMatch) {
      console.log(`   Found $$ selector: ${clickMatch[1]}`);
      return clickMatch[1];
    }

    console.log(`   ⚠️  Could not extract selector from generated code`);
    console.log(`   Generated code:\n${typescript.substring(0, 500)}...`);
    return null;
  }

  private extractFallbackSelectors(typescript: string): string[] {
    const fallbacks: string[] = [];

    // Look for selector arrays
    const arrayMatch = typescript.match(/selectors\s*=\s*\[([^\]]+)\]/);
    if (arrayMatch) {
      const selectorsStr = arrayMatch[1];
      const matches = selectorsStr.match(/['"]([^'"]+)['"]/g);
      if (matches) {
        fallbacks.push(...matches.map(s => s.replace(/['"]/g, '')));
      }
    }

    return fallbacks;
  }

  /**
   * Execute a phase using multiple strategies with adaptive fallback
   */
  private async executeWithStrategies(
    phase: any,
    strategies: string[]
  ): Promise<{ success: boolean; strategy_used?: string; error?: string }> {
    const attemptedStrategies: string[] = [];

    for (const strategy of strategies) {
      console.log(`🔄 Trying strategy: ${strategy}`);
      attemptedStrategies.push(strategy);

      try {
        // Here we would implement the actual strategy execution
        // For now, this is a placeholder that would be filled in with actual implementation
        // In a real implementation, this would use the sandbox to try the strategy

        // Simulate execution (this would be replaced with actual implementation)
        await new Promise(resolve => setTimeout(resolve, 1000));

        console.log(`✅ Strategy succeeded: ${strategy}`);
        return { success: true, strategy_used: strategy };

      } catch (error: any) {
        console.log(`❌ Strategy failed: ${strategy} - ${error.message}`);
        // Continue to next strategy
      }
    }

    // All strategies failed - ask AI for alternative
    console.log('\n🤖 All strategies failed. Asking AI for alternative approach...\n');

    const alternative = await this.deepseek.findAlternativeStrategy(
      phase.phase,
      'All primary and fallback strategies failed',
      attemptedStrategies
    );

    console.log(`💡 AI suggests: ${alternative.alternative_strategy}`);
    console.log(`   Reason: ${alternative.explanation}`);
    console.log(`   Confidence: ${alternative.confidence}\n`);

    if (alternative.confidence === 'high' || alternative.confidence === 'medium') {
      // Try the AI-suggested alternative
      console.log(`🔄 Trying AI-suggested alternative...`);
      try {
        // Here we would implement the alternative strategy
        // For now, this is a placeholder
        await new Promise(resolve => setTimeout(resolve, 1000));

        console.log(`✅ AI alternative succeeded!`);
        return { success: true, strategy_used: alternative.alternative_strategy };

      } catch (error: any) {
        console.log(`❌ AI alternative also failed: ${error.message}`);
      }
    }

    return {
      success: false,
      error: 'All strategies exhausted, including AI suggestions'
    };
  }

  private async fixFailedStep(
    originalStep: any,
    executionResult: any
  ): Promise<any | null> {
    console.log('🔧 Asking AI to diagnose and fix the error...');

    const diagnosis = await this.deepseek.diagnoseError({
      step_code: originalStep.typescript,
      error: executionResult.error || 'Step execution failed',
      selector: this.extractSelector(originalStep.typescript)
    });

    if (!diagnosis.fixable) {
      console.log(`❌ AI says error is not fixable: ${diagnosis.reason}`);
      return null;
    }

    console.log(`💡 Fix suggestion: ${diagnosis.explanation}`);

    // For now, return null (in production, AI would generate fixed code)
    return null;
  }

  private extractFunctionName(typescript: string): string {
    const match = typescript.match(/export\s+async\s+function\*\s+(\w+)/);
    return match ? match[1] : 'unknown_function';
  }

  private extractSelector(typescript: string): string {
    const match = typescript.match(/waitForSelector\(['"]([^'"]+)['"]/);
    return match ? match[1] : '';
  }

  private extractActionDescription(step: any): string {
    // Extract a human-readable description from the code
    const funcName = this.extractFunctionName(step.typescript);
    return funcName.replace(/_/g, ' ');
  }

  private async compileBotFiles(context: BotGenerationContext, botName: string): Promise<BotFiles> {
    const outputDir = `./generated_bots/${botName}`;

    console.log('📦 Compiling bot files...');

    // Read the existing template files (they already have steps 0 and 1)
    const yamlPath = `${outputDir}/${botName}_steps.yaml`;
    const tsPath = `${outputDir}/${botName}_impl.ts`;

    // The files already exist from the template initialization
    // The AI-generated steps have been appended during generation
    // So we just need to read them and return them

    try {
      const yamlContent = await fs.readFile(yamlPath, 'utf8');
      const tsContent = await fs.readFile(tsPath, 'utf8');

      console.log(`✅ Bot files compiled successfully`);
      console.log(`📁 Location: ${outputDir}`);
      console.log(`   • ${botName}_steps.yaml (${context.generated_steps.length + 2} steps total)`);
      console.log(`   • ${botName}_impl.ts`);
      console.log(`   • ${botName}_config.json`);
      console.log(`   • ${botName}_selectors.json\n`);

      return {
        yaml: yamlContent,
        typescript: tsContent,
        botName
      };
    } catch (error: any) {
      throw new Error(`Failed to compile bot files: ${error.message}`);
    }
  }

  private async saveBotProgress(context: BotGenerationContext, url: string, intent: string, botName: string): Promise<void> {
    if (!this.currentBotId) return;

    const metadata: BotMetadata = {
      id: this.currentBotId,
      name: botName,
      url,
      original_intent: intent,
      created_at: Date.now(),
      updated_at: Date.now(),
      status: 'in_progress',
      current_step: context.current_step,
      total_steps: context.generated_steps.length,
      generated_steps: context.generated_steps.map(s => ({
        step_number: s.step_number,
        action_description: s.action_description,
        yaml: s.yaml,
        typescript: s.typescript,
        execution_result: s.execution_result
      })),
      user_feedback: [],
      yaml_path: `./generated_bots/${botName}/${botName}_steps.yaml`,
      typescript_path: `./generated_bots/${botName}/${botName}_impl.ts`,
      context_path: `./generated_bots/${botName}/context.json`
    };

    await this.storage.saveBotMetadata(metadata);
  }

  async listBots(): Promise<BotMetadata[]> {
    return await this.storage.listBots();
  }

  async getBotsByUrl(url: string): Promise<BotMetadata[]> {
    return await this.storage.getBotsByUrl(url);
  }
}
